site_name: The Linac
site_url: https://thelinac.com
site_author: Peter B. Nguyen
theme:
  name: material
  palette:
    primary: blue
    accent: blue
  icon:
    logo: material/radioactive-circle
  features:
    - navigation.instant
    - navigation.tracking
    - search.suggest
    - search.highlight
    - content.tooltips

plugins:
  - search

markdown_extensions:
  - admonition
  - pymdownx.details
  - md_in_html
  - footnotes
  - tables
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.keys
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.smartsymbols:
      trademark: true
      copyright: true
      registered: true
      care_of: true
      plusminus: true
      arrows: true
      notequal: true
      fractions: true
      ordinal_numbers: true
  - attr_list
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - def_list
  - pymdownx.tasklist:
      custom_checkbox: true
  - abbr
  - pymdownx.snippets:
      auto_append:
        - includes/abbreviations.md
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.superfences

watch:
  - includes